# Generated by Django 5.1.5 on 2026-07-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('user_message', models.TextField(blank=True, null=True)),
                ('ai_response', models.TextField()),
                ('is_missed_call', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_number', models.IntegerField()),
                ('Language', models.CharField(max_length=200)),
                ('Service_Type', models.CharField(max_length=200)),
            ],
        ),
    ]
