# Generated by Django 5.1.5 on 2026-08-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='sheet_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='source',
            field=models.CharField(default='WhatsApp', max_length=50),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='status',
            field=models.CharField(default='Received', max_length=50),
        ),
    ]
