# Generated by Django 6.0.7 on 2026-08-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request', '0002_messagelog_sheet_synced_messagelog_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
