# Generated by Django 5.1.5 on 2026-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request', '0003_alter_messagelog_id_alter_userrequest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTemplate',
            fields=[
                ('template_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('meta_template_name', models.CharField(max_length=200)),
                ('library', models.CharField(max_length=50)),
                ('message_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('treatment', models.CharField(blank=True, max_length=100)),
                ('objection', models.CharField(blank=True, max_length=100)),
                ('trigger', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=50)),
                ('header_type', models.CharField(blank=True, max_length=50)),
                ('header_text', models.TextField(blank=True)),
                ('meta_approved_body', models.TextField()),
                ('cta_type', models.CharField(blank=True, max_length=50)),
                ('cta_value', models.CharField(blank=True, max_length=200)),
                ('media_type', models.CharField(blank=True, max_length=50)),
                ('media_asset_id', models.CharField(blank=True, max_length=100)),
                ('variable_mapping', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('ai_personalization_inputs', models.TextField(blank=True)),
                ('ai_writing_rules', models.TextField(blank=True)),
                ('workflow_exit_condition', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('meta_templates', models.TextField(blank=True)),
                ('meta_mapping', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['library'], name='user_reques_library_aea420_idx'), models.Index(fields=['category'], name='user_reques_categor_1ad144_idx'), models.Index(fields=['trigger'], name='user_reques_trigger_293b39_idx'), models.Index(fields=['treatment'], name='user_reques_treatme_679067_idx'), models.Index(fields=['objection'], name='user_reques_objecti_ec1655_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('current_library', models.CharField(blank=True, max_length=50)),
                ('current_step', models.IntegerField(default=0)),
                ('last_template_id', models.CharField(blank=True, max_length=50)),
                ('treatment', models.CharField(blank=True, max_length=100)),
                ('objection', models.CharField(blank=True, max_length=100)),
                ('appointment_booked', models.BooleanField(default=False)),
                ('last_message_date', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number'], name='user_reques_phone_n_626e94_idx'), models.Index(fields=['current_library'], name='user_reques_current_b04257_idx')],
            },
        ),
    ]
