# Generated by Django 5.1.5 on 2026-08-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request', '0004_metatemplate_workflowstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatemplate',
            name='media_asset_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='metatemplate',
            name='template_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
